USE MASTER
GO

IF EXISTS (SELECT * FROM sys.databases WHERE NAME = 'Pharmacies')
DROP DATABASE Pharmacies
GO

CREATE DATABASE Pharmacies
GO

USE Pharmacies
GO

CREATE TABLE COMPANY(
	CompanyID INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(20) NOT NULL,
)
GO
CREATE TABLE DRUG(
	DrugID INT PRIMARY KEY IDENTITY(1,1),
	DrugName NVARCHAR(20) NOT NULL,
	CompanyID INT NOT NULL,
	CONSTRAINT FK_DRUG_COMPANY FOREIGN KEY(CompanyID) REFERENCES COMPANY(CompanyID)
)
GO
CREATE TABLE PHARMACY(
	PharmacyID INT PRIMARY KEY IDENTITY(1,1),
	PharmacyName NVARCHAR(20) NOT NULL,
	)
GO
CREATE TABLE DRUG_PHARMACY(
	DrugID INT,
	PharmacyID INT,
	PRIMARY KEY(DrugID,PharmacyID),
	CONSTRAINT FK_DRUG_PHARMACY_PHARMACY FOREIGN KEY(PharmacyID) REFERENCES PHARMACY(PharmacyID),
	CONSTRAINT FK_DRUG_PHARMACY_DRUG FOREIGN KEY(DrugID) REFERENCES DRUG(DrugID)
)
GO
CREATE TABLE RECORD(
	RecordID INT PRIMARY KEY IDENTITY(1,1),
	DoctorID INT NOT NULL,
	PatientID INT NOT NULL,
	Date DATETIME NOT NULL
)
GO

CREATE TABLE DETAILRECORD(
	RecordID INT,
	DrugID INT,
	PRIMARY KEY(RecordID,DrugID),
	CONSTRAINT FK_DETAILRECORD_RECORD FOREIGN KEY(RecordID) REFERENCES RECORD(RecordID),
	CONSTRAINT FK_DETAILRECORD_DRUG FOREIGN KEY(DrugID) REFERENCES DRUG(DrugID)
)
GO
CREATE TABLE DOCTOR(
	DoctorID INT PRIMARY KEY IDENTITY(1,1),
	DortorName NVARCHAR(20)NOT NULL,
)
GO
CREATE TABLE PATIENT(
	PatientID INT PRIMARY KEY IDENTITY(1,1),
	PatientIDName NVARCHAR(20)NOT NULL,
)
GO

ALTER TABLE RECORD ADD CONSTRAINT FK_DOCTOR_RECORD FOREIGN KEY(DoctorID) REFERENCES DOCTOR(DoctorID)
GO
ALTER TABLE RECORD ADD CONSTRAINT FK_PATIENT_RECORD FOREIGN KEY(PatientID) REFERENCES PATIENT(PatientID)
GO

CREATE TABLE CONSTRACT(
	CompanyID INT,
	PharmacyID INT,
	PRIMARY KEY(CompanyID,PharmacyID),
	Startdate DATETIME NOT NULL,
	LongTime INT NOT NULL
	CONSTRAINT FK_CONSTRACT_COMPANY FOREIGN KEY(CompanyID) REFERENCES COMPANY(CompanyID),
	CONSTRAINT FK_CONSTRACT_PHARMACY FOREIGN KEY(PharmacyID) REFERENCES PHARMACY(PharmacyID)
)
GO