USE MASTER
GO

IF EXISTS (SELECT * FROM sys.databases WHERE NAME = 'EX3')
DROP DATABASE EX3
GO

CREATE DATABASE EX3
GO

USE EX3
GO

CREATE TABLE Test(
	ID INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(20) NOT NULL,
	Code VARCHAR(5) CHECK(LEN(Code)=5) UNIQUE,
	ModifielDate DATETIME NOT NULL
)
GO
INSERT INTO Test VALUES(N'Phoden',N'RDT43','2020/01/12')
